language: python
cache: pip
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script: "make test VENV_BIN=''"
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - redis-server
env:
  - REDIS_URL=localhost:6379
  - DEBUG=True
