language: python
python:
  - "3.5"
install:
  - pip install python-coveralls
script: "make test"
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - redis-server
env:
  - REDIS_URL=localhost:6379
