redis:
  image: redis:3.0.7-alpine
  command: redis-server --appendonly yes
  volumes:
    - "data:/data"
  ports:
    - "3679:3679"
web:
  build: .
  command: /app-ve/bin/python /app/manage.py runserver 0.0.0.0:8000
  volumes:
      - .:/app/
  ports:
      - "8000:8000"
  links:
    - redis
