redis:
  image: redis:3.0.7-alpine
  command: ["redis-server", "--appendonly", "yes"]
web:
  build: .
  #command: /app/projects/serve.sh
  volumes:
      - .:/app/
      - ./data:/data/
  ports:
    - "80:8000"
  environment:
    - DB_NAME=/data/container.db
    - DEBUG=True
    - GUNICORN_WORKERS=10
  links:
    - redis
