# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsummary',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
